Odstranene nekonecne while loops. Nahradene timeoutom + kubectl vytvaranie zo sablony s 3xretry pri chybach.

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -28,7 +28,27 @@ function create_from_template {
     shift
   done
 
-  kubectl create -f "${TMP_DIR}/$(basename $FILE)"
+  ERROR=0
+  for i in $(seq 1 3)
+  do
+    kubectl create -f "${TMP_DIR}/$(basename $FILE)"
+
+    # TODO What are return values for specific error - timeout/unreachable,... ?
+    if [ $? -ne 0 ]; then
+      echo "Error while creating a template ${TMP_DIR}/$(basename $FILE) !"
+      echo "Retrying..."
+      ERROR=1
+      sleep 10
+    else
+      ERROR=0
+      break
+    fi
+  done
+
+  if [ "$ERROR" -eq 1 ]; then
+    echo "Error while creating a template ${TMP_DIR}/$(basename $FILE) !"
+    exit 1
+  fi
 }
 
 function setup_credentials {
@@ -59,11 +79,11 @@ function wait_for_deployment_ready()
   NAMESPACE=$1
   LABEL=$2
 
-  while true
+  for i in $(seq 1 30)
   do
     COUNT=$(kubectl get deployment --no-headers -o=custom-columns=AVAILABLE:.status.availableReplicas -l $LABEL -n $NAMESPACE)
     [ $COUNT -gt 0 ] && break
-    sleep 10
+    sleep 60
   done
 }
 
@@ -101,14 +121,12 @@ function install_ingress_controller {
 function wait_for_ingress_controller_public_ip {
   # Wait for public IP address of nginx ingress service
   ROUTER_IP=''
-  COUNTER=1
-  while true
+  for COUNTER in $(seq 1 30)
   do
     ROUTER_IP=$(kubectl get service -o=custom-columns=LB_IP:.status.loadBalancer.ingress[*].ip,TYPE:.spec.type --no-headers -l app=nginx-ingress -n ${INGRESS_NAMESPACE} | grep LoadBalancer | awk '{ print $1 }' | head -n1)
     [ "$ROUTER_IP" != "<pending>" ] && [ "$ROUTER_IP" != "<none>" ] && break
     echo "Waiting for public IP of ingress router service. (#${COUNTER})"
-    let COUNTER=$COUNTER+1
-    sleep 10
+    sleep 60
   done
 }
 
@@ -126,9 +144,9 @@ function install_cert_manager {
 
   # CA cluster issuer.
   # Wait till cluster issuer resource can be created.
-  while true; do
+  for i in $(seq 1 30)
     kubectl apply -f templates/ingress/cluster-issuer.yaml && break
-    sleep 10
+    sleep 60
   done
 }
 
